//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaconScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconScore
    {
        public int BeaconId { get; set; }
        public string TestType { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Feedback { get; set; }
        public System.DateTime Date { get; set; }
        public string HROM { get; set; }
        public string Location { get; set; }
        public string Result { get; set; }
        public int VacancyID { get; set; }
    }
}
